### ISSUE TITLE
Brightcove not returning TenPlay videos

### ISSUE THREAD

**Issue by aplund** [xbmc-catchuptv-au/repo#21]
I've narrowed this error down to the NoneType being returned by the Brightcove api.  I haven't been able to figure out why this is happening however.  It happens when going into the videolist for any TenPlay items.

>22:42:22 T:1633763888   ERROR: [plugin.video.catchuptv.au.ten] Traceback (most recent call last):
>                                              File "/var/lib/kodi/.kodi/addons/plugin.video.catchuptv.au.ten/resources/lib/networktenaddon/__init__.py", line 49, in run
>                                                self.plugin.run()
>                                              File "/var/lib/kodi/.kodi/addons/script.module.xbmcswift2/lib/xbmcswift2/plugin.py", line 332, in run
>                                                items = self._dispatch(self.request.path)
>                                              File "/var/lib/kodi/.kodi/addons/script.module.xbmcswift2/lib/xbmcswift2/plugin.py", line 306, in _dispatch
>                                                listitems = view_func(**items)
>                                              File "/var/lib/kodi/.kodi/addons/plugin.video.catchuptv.au.ten/resources/lib/networktenaddon/videolist.py", line 74, in videolist
>                                                for video in videos.items:
>                                            TypeError: 'NoneType' object is not iterable

**Comment by AuXBoX** [comment]
I'm too getting this error

**Comment by aplund** [comment]
I had a quick look at this last night but I don't have time to track it down.
Is there a way of seeing what brightcove is returning?  Is it just not working for TenPlay anymore, or has there been a change in the search criteria?

**Comment by aplund** [comment]
I had another look at this and the Brightcove request returns the following error:

> com.brightcove.templating.PlayerAccessDeniedException : Attempt to access inactive Player, ID:2371615070001

So there must have been some magic numbers change that is responsible for this.
