### ISSUE TITLE
TenPlay No longer working

### ISSUE THREAD

**Issue by supmaxi** [xbmc-catchuptv-au/repo#27]
When clicking on any stream I get the following error:

global name 'Video' is not defined
[run (49)]
Would you like to report this issue?

Also, sometimes the folders dont open at all.
This use to work great, hoping someone can help :)) Thanks for the hard work btw, we need more great aussie developers like yourselves

**Comment by xdegenerate** [comment]
I've got the exact same issue, too. 

Can someone please help us out here?

I'm using a standard android box, MQ something or other? Id exact details are needed, I can provide them if asked. 

Whats weird is it works fine on one box we have, but the other will just not play ball.

**Comment by glennguy** [comment]
Tenplay no longer uses RTMP so that's not the issue. If you could follow the [log upload guide(http://kodi.wiki/view/Log_file/Easy) and post the link we might be able to find the cause.

**Comment by xdegenerate** [comment]
I've been trying to upload a log. The guide you linked me too says its called "Kodi-Log Uploader", however I presume it's been changed to "Kodi Log E-mailer" as I cannot find anything with the other name. I installed that, entered my e-mail, and have been trying to upload it; both to myself and to another e-mail, but I just keep getting an "error". It just wont log in and upload anything for me. My email and password are correct, i've checked it a million times, and tried alternate e-mails, and I have selected both yahoo and gmail and hotmail etc in the drop down box. It just wont upload it. 

Is there a way I can copy and paste it to a USB to upload it somehow?

**Comment by xdegenerate** [comment]
I think I did this right. 

[lS+aFDee.txt](https://github.com/xbmc-catchuptv-au/repo/files/812324/lS.aFDee.txt)

**Comment by andybotting** [comment]
Nice work @xdegenerate that's it.


```09:42:46 T:1926048352   ERROR: [plugin.video.catchuptv.au.ten] Traceback (most recent call last):
  File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.catchuptv.au.ten/resources/lib/networktenaddon/__init__.py", line 49, in run
    self.plugin.run()
  File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.xbmcswift2/lib/xbmcswift2/plugin.py", line 332, in run
    items = self._dispatch(self.request.path)
  File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.xbmcswift2/lib/xbmcswift2/plugin.py", line 306, in _dispatch
    listitems = view_func(**items)
  File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.catchuptv.au.ten/resources/lib/networktenaddon/play.py", line 42, in play
    media = api.get_media_for_video(videoId)
  File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.catchuptv.au.ten/resources/lib/networktenvideo/api.py", line 271, in get_media_for_video
    video = self.brightcove.find_video_by_id(videoId, fields='renditions', media_delivery='http')
  File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.catchuptv.au.ten/resources/lib/brightcove/api.py", line 64, in find_video_by_id
    params = validate_params(**locals())
  File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.catchuptv.au.ten/resources/lib/brightcove/utils.py", line 16, in validate_params
    params[key] = getattr(Validators, key)(val)
  File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.catchuptv.au.ten/resources/lib/brightcove/utils.py", line 71, in fields
    assert field in Video._fields, (
NameError: global name 'Video' is not defined
```

**Comment by xdegenerate** [comment]
thanks... is there a way i can fix it?

**Comment by glennguy** [comment]
Yes! :smiley: I've tested the add-on with Kodi 14.2 for Android and can reproduce the issue. The easy solution is to upgrade Kodi. I've tested on 16.1 with success but since 17 is out you should just go straight to that.

**Comment by xdegenerate** [comment]
ok, thanks, i'll give that a try.

**Comment by xdegenerate** [comment]
That did the trick! Thank you very much, glennguy
