### ISSUE TITLE
Plus7 'NoneType' has no attribute 'replace' 

### ISSUE THREAD

**Issue by NCopeman** [xbmc-catchuptv-au/repo#31]
On both my OpenELEC Raspberry Pi and My PC running Kodi 15, I get this error when selecting the title of a series. It occurs for the majority of titles.
```

19:49:49 T:512340  NOTICE: [Plus7 v2.8] XBMC 15.1 running on Windows
19:49:50 T:512340  NOTICE: [Plus7 v2.8] Showing programs list for autv-plus7-my-france-with-manu
19:49:50 T:512340  NOTICE: [Plus7 v2.8] Traceback (most recent call last):
                                              File "C:\Users\Nathan\AppData\Roaming\Kodi\addons\plugin.video.plus7\resources\lib\programs.py", line 46, in make_programs_list
                                                listitem.setInfo('video', p.get_xbmc_list_item())
                                              File "C:\Users\Nathan\AppData\Roaming\Kodi\addons\plugin.video.plus7\resources\lib\classes.py", line 223, in get_xbmc_list_item
                                                if self.get_description():   d['plot'] = self.get_description()
                                              File "C:\Users\Nathan\AppData\Roaming\Kodi\addons\plugin.video.plus7\resources\lib\classes.py", line 138, in get_description
                                                return utils.descape(self.description)
                                              File "C:\Users\Nathan\AppData\Roaming\Kodi\addons\plugin.video.plus7\resources\lib\utils.py", line 48, in descape
                                                string = string.replace('&#38;', '&amp;')
                                            AttributeError: 'NoneType' object has no attribute 'replace'
```

**Comment by andybotting** [comment]
Thanks. I think this should be fixed in v3.0.0 that I've just pushed to the repo. Can you confirm if it solves your issue?

**Comment by bak0z** [comment]
Hi Andy, v3.0.0 does fix this issue with plus7.

**Comment by NCopeman** [comment]
Yep! Definitely solves it. Keep up the fantastic work! :)
