### ISSUE TITLE
Error Type: <class 'cryptography.exceptions.InternalError'>

### ISSUE THREAD

**Issue by sportswriter** [xbmc-catchuptv-au/repo#67]
Hi - any thoughts on this error message from the kodi log?  I've installed iview & sbs-on-demand.  An error message appears on the kodi UI when I try to navigate to one of the directories (such as "ABC ARTS")

thanks

11:44:37.038 T:140403932120832   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'cryptography.exceptions.InternalError'>
                                            Error Contents: Unknown OpenSSL error. Please file an issue at https://github.com/pyca/cryptography/issues with information on how to reproduce this. ([_OpenSSLError(code=621174887L, lib=37, func=102, reason=103), _OpenSSLError(code=621215847L, lib=37, func=112, reason=103), _OpenSSLError(code=638279812L, lib=38, func=182, reason=132), _OpenSSLError(code=637968500L, lib=38, func=106, reason=116)])
                                            Traceback (most recent call last):
                                              File "/home/kodi/.kodi/addons/plugin.video.abc_iview/default.py", line 33, in <module>
                                                import categories  # noqa: E402
                                              File "/home/kodi/.kodi/addons/plugin.video.abc_iview/resources/lib/categories.py", line 22, in <module>
                                                import comm
                                              File "/home/kodi/.kodi/addons/plugin.video.abc_iview/resources/lib/comm.py", line 24, in <module>
                                                import requests
                                              File "/home/kodi/.kodi/addons/script.module.requests/lib/requests/__init__.py", line 84, in <module>
                                                from urllib3.contrib import pyopenssl
                                              File "/home/kodi/.kodi/addons/script.module.urllib3/lib/urllib3/contrib/pyopenssl.py", line 48, in <module>
                                                from cryptography.hazmat.backends.openssl import backend as openssl_backend
                                              File "/usr/lib/python2.7/dist-packages/cryptography/hazmat/backends/openssl/__init__.py", line 7, in <module>
                                                from cryptography.hazmat.backends.openssl.backend import backend
                                              File "/usr/lib/python2.7/dist-packages/cryptography/hazmat/backends/openssl/backend.py", line 2299, in <module>
                                                backend = Backend()
                                              File "/usr/lib/python2.7/dist-packages/cryptography/hazmat/backends/openssl/backend.py", line 716, in __init__
                                                self.activate_osrandom_engine()
                                              File "/usr/lib/python2.7/dist-packages/cryptography/hazmat/backends/openssl/backend.py", line 738, in activate_osrandom_engine
                                                self.openssl_assert(e != self._ffi.NULL)
                                              File "/usr/lib/python2.7/dist-packages/cryptography/hazmat/backends/openssl/backend.py", line 719, in openssl_assert
                                                return binding._openssl_assert(self._lib, ok)
                                              File "/usr/lib/python2.7/dist-packages/cryptography/hazmat/bindings/openssl/binding.py", line 43, in _openssl_assert
                                                errors
                                            InternalError: Unknown OpenSSL error. Please file an issue at https://github.com/pyca/cryptography/issues with information on how to reproduce this. ([_OpenSSLError(code=621174887L, lib=37, func=102, reason=103), _OpenSSLError(code=621215847L, lib=37, func=112, reason=103), _OpenSSLError(code=638279812L, lib=38, func=182, reason=132), _OpenSSLError(code=637968500L, lib=38, func=106, reason=116)])
                                            -->End of Python script error report<--
11:44:37.084 T:140405860206976   ERROR: GetDirectory - Error getting plugin://plugin.video.abc_iview/?category=channel%2fabcarts
11:44:37.085 T:140405860206976   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.abc_iview/?category=channel%2fabcarts) failed
11:44:37.587 T:140403932120832  NOTICE: [ABC iView v1.8.5] Kodi 17.6 running on Linux
11:44:37.587 T:140403932120832  NOTICE: [ABC iView v1.8.5] Performing GET for http://iview.abc.net.au/api/navigation/mobile/2/?device=hbb&hbr=1
11:44:39.382 T:140403932120832  NOTICE: [ABC iView v1.8.5] Kodi 17.6 running on Linux
11:44:39.382 T:140403932120832  NOTICE: [ABC iView v1.8.5] Getting programme from feed (channel/abcarts)
11:44:39.542 T:140403932120832  NOTICE: [ABC iView v1.8.5] Performing GET for http://iview.abc.net.au/api/channel/abcarts?device=hbb&hbr=1&sort=az
11:44:41.820 T:140403932120832  NOTICE: [ABC iView v1.8.5] Performing GET for http://iview.abc.net.au/api/index?device=hbb&hbr=1&fields=seriesTitle,episodeCount,href

**Comment by glennguy** [comment]
Hi @sportswriter 

It's a problem outside of our addons, but I think I've tracked down the right solution for you:
```sudo pip install pyopenssl -U```
That should hopefully get you sorted! Let me know how you go

Thanks

Glenn

**Comment by sportswriter** [comment]
Thanks - that did the trick.
